apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "blackpandi20037@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "cfyr usmk mmht zlyi"
type: Opaque
